# Generated by Django 5.1.7 on 2025-04-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('EGP', 'Egyptian Pounds'), ('USD', 'US Dollars')], default='EGP', max_length=3),
        ),
    ]
