# Generated by Django 5.1.7 on 2025-04-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_project_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='currency',
        ),
    ]
