# Generated by Django 5.1.7 on 2025-04-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='code',
            new_name='id',
        ),
    ]
